### ISSUE TITLE
Нерабочая ссылка на спецификации устройств

### ISSUE THREAD

**Issue by ipon85** [evotor/documentation-v2#50]
https://developer.evotor.ru/docs/%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B0%D0%BD%D0%B0%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%81%D0%BE%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F%D0%BC%D0%B8%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2.

**Comment by Lytkini** [comment]
Спасибо!

Ссылка исправлена здесь:
https://developer.evotor.ru/docs/doc_java_app_development_prerequisites.html

Pull request:
https://github.com/evotor/documentation-v2/pull/52

**Comment by ipon85** [comment]
Спасибо.

пн, 2 сент. 2019 г. в 16:21, Lytkini <notifications@github.com>:
