### ISSUE TITLE
Добавление extraKeys не работает так, как указано в документации. 

### ISSUE THREAD

**Issue by Worik42** [evotor/documentation-v2#77]
Мне нужно добавить дополнительные поля в позиции в чеке. 
val extraKeys: Set<ExtraKey> = hashSetOf(
                ExtraKey("object", null, it.`object`.toString()),
                ExtraKey("method", null, it.method.toString())
            )
positionAddList.add(
                PositionAdd(
                    Position.Builder.newInstance(
                        UUID.randomUUID().toString(), null,
                        it.label,
                        "",
                        0,
                        BigDecimal(it.price),
                        BigDecimal(it.quantity)
                    ).setExtraKeys(extraKeys).setTaxNumber(vat).build()

-----------------------------------------------------
На сервисе печати чека продажи. 
 val r = ReceiptApi.getReceipt(applicationContext, Receipt.Type.SELL)
for (p in r.getPositions()) {
  val list = ArrayList(p.extraKeys)
}

соответственно при печати extraKeys пустой

**Comment by xcam** [comment]
У вас appid = null, а должен быть равен uuid приложения из androidmanifest

**Comment by Worik42** [comment]
> У вас appid = null, а должен быть равен uuid приложения из androidmanifest

Спасибо.
